services:
  app:
    build: .
    container_name: test-backend-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=pusdatin_keluarga
    restart: always

  db:
    image: postgres:16
    container_name: test-backend-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pusdatin_keluarga
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  scheduler:
    build: .
    container_name: test-backend-scheduler
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=pusdatin_keluarga
    command: ["sh", "-c", "echo '*/15 * * * * /app/ingest.sh' > /etc/crontabs/root && crond -f -L /dev/stdout"]
    restart: always
   # Nginx untuk serve HTML static
  nginx:
    image: nginx:alpine
    ports:
      - "3003:80"
    volumes:
      - ./static:/usr/share/nginx/html
    depends_on:
      - app

volumes:
  db_data:
